##############################
#       Spring Config        #
##############################

spring:
 h2.console.enabled: true
 datasource:
  url: jdbc:h2:tcp://localhost:1521/podcast-server
  username: sa
  driver-class-name: org.h2.Driver
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: false
  hibernate.ddl-auto: update
  properties :
   jadira.usertype.autoRegisterUserTypes: true
   hibernate:
    event.merge.entity_copy_observer: allow
    format_sql: true
    search.default:
      indexmanager: near-real-time
      directory_provider: local-heap
      indexBase: /tmp/podcast-server/lucene
 servlet.multipart:
  location: ${java.io.tmpdir}
  max-file-size: 512MB
  max-request-size: 512MB

server:
 port: 8080

logging:
 path: /tmp/podcast-server/podcast-server.log
 level:
  lan.dk.podcastserver : DEBUG

management:
  endpoint:
    health.show-details: always
  endpoints.web.exposure.include: ['health', 'info', 'env']


##############################
#    Application Specific    #
##############################

podcastserver:
 rootfolder: /tmp/podcast-server/
 #concurrent-download: 2
 max-update-parallels: 256
 #cover-default-name: cover
 number-of-day-to-download: 30
 number-of-day-to-save-cover: 30
 #number-of-try: 10
 #download-extension: .psdownload
 #rss-default-number-item: 50
 update-and-download.refresh.cron: 0 0 0 * * ?
 backup :
  location: /tmp/podcast-server/backup/
  cron: 0 30 4 * * ?
  binary: false
  enabled: false
 externaltools:
  #rtmpdump: /usr/local/bin/rtmpdump
  #ffmpeg: /usr/local/bin/ffmpeg
  #ffprobe: /usr/local/bin/ffprobe
